异常


Exception
Java代码在运行时期发生的问题就是异常

异常的继承体系
	Throwable类: 它是所有错误与异常的超类（祖宗类）
		|- 子类Error: 错误 服务器可能会宕机
		|- 子类Exception: 编译期异常（受查异常）,进行编译JAVA程序时出现的问题，必须进行try ..catch进行处理，如果不处理，程序就不能编译通过。
			|- RuntimeException 运行期异常（非受查异常）：Java编译器不会检查它，也就是说:
			                                         当程序中可能出现这类异常，即使没有用try-catch语句捕获它，
													 也没有用throws子句声明抛出它，也会编译通过。

区别：	
编译异常：是因为程序没有遵循语法规则，编译程序能够自己发现并且提示我们错误的原因和位置，这个也是大家在刚接触编程语言最常遇到的问题。
运行时异常：是因为程序在执行时，运行环境发现了不能执行的操作。
								
异常的处理方式：
	1.JVM的默认处理方式
		把异常的名称,原因,位置等信息输出在控制台，同时会结束程序。[一旦有异常发生，其后来的代码不能继续执行]
	2.解决程序中异常的手动方式：	[处理完异常，其后来的代码可以继续执行]
		1.抛出 throw 异常对象，throws 异常类
		2.编写处理代码 try...catch...finally
		
			   
### 捕获处理异常
1.直接抛给调用者 throw/throws
2.自己处理 try...catch

#### throw/throws   
throw关键字
[throw 用在方法内]，用来抛出一个异常对象，将这个异常对象传递到调用者处，并结束当前方法的执行。
	
格式：
    throw new 异常类名(参数);	
	例：
	throw new NullPointerException("要访问的arr数组不存在");


throws关键字-->方法申明
[throws 用在方法申明]，将问题标识出来，报告给调用者。 

格式：
	修饰符 返回值类型 方法名(参数) throws 异常类名1,异常类名2… {   
	    //方法体
	}  
	异常类名1,异常类名2 就是调用这个方法有可能出现的问题

#### try...catch
对异常的语句进行捕获，可以对出现的异常进行指定方式的处理

格式：
	try {
		//有可能出现问题的代码
	}
	catch(异常类 变量) { //有可能出现的异常
		//出了问题后做哪些操作
	}…	//可以多个catch  从小到大 Exception最大
	finally {
		//一定会被执行的语句。	
	}

关键字：
try：      用于捕获异常。其后可接零个或多个catch块，如果没有catch块，则必须跟一个finally块。
catch：    用于处理try捕获到的异常。
finally：  无论是否捕获或处理异常，finally块里的语句都会被执行。
				 		
注：
1.try中有多个异常语句，只能执行第一个异常语句，也只能返回一种处理结果
2.当catch没有捕获到对应的异常时,程序还是异常出错,其后代码不会被执行
3.finally不管异常都会执行
																
在以下4种特殊情况下，finally块不会被执行：
1: 在finally语句块中发生了异常。
2: 在前面的代码中用了System.exit()退出程序。
3: 程序所在的线程死亡。
4: 关闭CPU。

	
关于return的顺序问题:	
总结：当在try块或catch块中遇到return语句时，finally语句块将在方法返回之前被执行。

示例:
```java
public class A{
    public static int test(){
    	try {
    		System.out.println("try block");	//1
    		int i = 1 / 0; 						//2
    		return 0;							//3
    	} catch (Exception e) {
    		System.out.println("catch block");	//4
    		return 1;							//5
    	} finally {
    		System.out.println("finally block");//6
    		return 2;							//7
    	}
    }
}
```
结果：
try block
catch block
finally block
2

过程：
先输出“1”，到“2”时发生异常，则输出“4”，然后输出“5”放在缓冲区中等待，
然后输出“6”，再输出“7”改变了缓冲区中原来的返回值，再输出。
假如没有“7”，则最后结果会返回“5”的值。


### 自定义异常
定义：
继承 Exception 和 RuntimeException 都可以，RuntimeException 使用时就不需要抛

```java
@Data
public class PdpServerException extends RuntimeException {

    public static final Integer FAIL_CODE = 40000;

    private Integer code;
    private String msg;
    private Object data;

    public PdpServerException(String msg) {
        super(msg);
        this.code = FAIL_CODE;
        this.msg = msg;
    }

    public PdpServerException(Integer code, String msg) {
        super(msg);
        this.code = code;
        this.msg = msg;
    }

    public PdpServerException(String msg, Object data) {
        super(msg);
        this.code = FAIL_CODE;
        this.msg = msg;
        this.data = data;
    }

    public PdpServerException(Integer code, String msg, Object data) {
        super(msg);
        this.code = code;
        this.msg = msg;
        this.data = data;
    }
}
```


### 异常的使用
```java
public class A{
    public int test() throws PdpServerException{        //将自定义异常扔给框架，由统一异常处理捕获处理
    	try {
    		int i = 1 / 0; 	    //除0异常	
    	} catch (Exception e) {
    		throw new PdpServerException(e.getMessage); //捕获异常并抛出自定义的异常
    	} finally {
    		//....              //不管是否有异常都要执行的操作
    	}
    }
}
```


### 异常常见分类

#### 1. RuntimeException子类
序号	异常名称									    异常描述
1	java.lang.ArrayIndexOutOfBoundsException	数组索引越界异常。当对数组的索引值为负数或大于等于数组大小时抛出。
2	java.lang.ArithmeticException				算术条件异常。譬如：整数除零等。
3	java.lang.SecurityException					安全性异常
4	java.lang.IllegalArgumentException			非法参数异常
5	java.lang.ArrayStoreException				数组中包含不兼容的值抛出的异常
6	java.lang.NegativeArraySizeException		数组长度为负异常
7	java.lang.ClassNotFoundException			找不到类异常。当应用试图根据字符串形式的类名构造类，而在遍历CLASSPAH之后找不到对应名称的class文件时，
											    抛出该异常。
8	java.lang.NullPointerException				空指针异常。当应用试图在要求使用对象的地方使用了null时，抛出该异常。
											    譬如：调用null对象的实例方法、访问null对象的属性、计算null对象的长度、使用throw语句抛出null等等。

#### 2.IOException
序号	异常名称					异常描述
1	IOException				操作输入流和输出流时可能出现的异常
2	EOFException			文件已结束异常
3	FileNotFoundException	文件未找到异常


#### 3. 其他 
序号	异常名称							异常描述
1	ClassCastException				类型转换异常类
2	ArrayStoreException				数组中包含不兼容的值抛出的异常
3	SQLException					操作数据库异常类
4	NoSuchFieldException			字段未找到异常
5	NoSuchMethodException			方法未找到抛出的异常
6	NumberFormatException			字符串转换为数字抛出的异常
7	StringIndexOutOfBoundsException	字符串索引超出范围抛出的异常
8	IllegalAccessException			不允许访问某类异常
9	InstantiationException			当应用程序试图使用Class类中的newInstance()方法创建一个类的实例，而指定的类对象无法被实例化时，抛出该异常
